version: 2.1
jobs:
  build-and-test:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - run:
        name: Install Docker Compose
        environment:
          COMPOSE_VERSION: '1.29.2'
        command: |
          curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
          chmod +x ~/docker-compose
          sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - run:
        name: Build images of services declared in docker-compose.yml
        command: docker-compose build
      - run:
        name: Start all services declared in docker-compose.yml
        command: docker-compose up -d
      - run:
          name: Test djang
          command: |
            docker-compose -f docker-compose.yml run backend sh -c "python manage.py test"

workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-test


      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
