name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django>=2.1.3,<2.2.0
        pip install djangorestframework>=3.9.0,<3.10.0
        pip install psycopg2-binary
        pip install flake8>=3.6.0,<3.7.0
    - name: Run Tests
      run: |
        python app/manage.py test
