name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build
    - name: Install node
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Run tests
      run: python manage.py test
